### ISSUE TITLE
Create Table - user

### ISSUE THREAD

**Issue by andrea-e-c** [Drop-It-Like-Its-Propane/strickland-propane#51]
- [x] #71
- [x] Fill with seed data

**Name:** Users
**Fields:**
- [x] UserID: INT - PK
- [x] Name:TEXT - Required
- [x] Email: TEXT - validator - Required 
- [x] Password - Hashed - Required
- [x] Username - given
- [x] IsAdmin - Boolean - validator  required - default: No
- [x] Image: default: ??? URL

Methods:
- inst - Correct Password
- inst - Generate Token
- class - authenticate
- class - find by token

**Relationships:**
- Users have many orders
- orders belows to users

Example for admin validator from Pillars: 
isStudent:{
    type: Sequelize.VIRTUAL,
    get(){
      if(this.userType === 'TEACHER'){
        return false
      }else{
        return true
      }
    }
  },

**Comment by ItsEducational** [comment]
Done:
Table created
